# Positional Encoding

 - positional encoding은 문자의 위치정보를 인코딩하는 것으로 sin, cos 함수를 이용
 - Transformer 모델에서 처음으로 접했는데 해당 알고리즘이 명확히 이해가 되지 않아 아래 링크의 블로그를 참고해서 추가적으로 공부.
 - https://machinelearningmastery.com/a-gentle-introduction-to-positional-encoding-in-transformer-models-part-1/
 - https://gaussian37.github.io/dl-concept-positional_encoding/

$P(k, 2i) = \sin(\frac{k}{n^{2i/d}})$
$\\ P(k, 2i + 1) = \cos(\frac{k}{n^{2i/d}})$

In [2]:
# Coding the Positional Encoding Matrix from Scratch

import numpy as np
import matplotlib.pyplot as plt

def getPositionEncoding(seq_len, d, n=10000):
    # P = [0, 0, 0, 0] X4
    P = np.zeros((seq_len, d))

    for k in range(seq_len):
        for i in np.arange(int(d/2)):
            denominator = np.power(n, 2*i/d)
            P[k, 2*i] = np.sin(k/denominator)
            P[k, 2*i+1] = np.cos(k/denominator)
    return P

# 문장길이 : 4, output size = 4, 
P = getPositionEncoding(seq_len=4, d=4, n=100)
print(P)


[[ 0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.09983342  0.99500417]
 [ 0.90929743 -0.41614684  0.19866933  0.98006658]
 [ 0.14112001 -0.9899925   0.29552021  0.95533649]]


In [15]:
np.zeros((4, 4))
print(np.arange(int(4/2)))
print(np.power(4, 1.5))

[0 1]
8.0
