# 1. Tensor

In [1]:
import torch
import numpy as np

In [5]:
# 직접 생성
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [6]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4247, 0.7476],
        [0.1939, 0.1899]]) 



In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n {rand_tensor.shape} \n")
print(f"Ones Tensor: \n {ones_tensor} \n {ones_tensor.shape} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n {zeros_tensor.shape}")

Random Tensor: 
 tensor([[0.0669, 0.9981, 0.8338],
        [0.2049, 0.5495, 0.4410]]) 
 torch.Size([2, 3]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 torch.Size([2, 3]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 torch.Size([2, 3])


In [10]:
# 텐서의 속성(Attribute)
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [22]:
tensor = torch.rand(4, 4)

In [37]:
# 텐서의 연산(Operation)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# 슬라이싱을 실행할 때, 2차원이면 [ 1dim, 2dim]의 형태에서 [ x:y, x:y]의 형태로 슬라이싱을 실행할 수 있다.
# ':' 하나만 입력하면 전체를 뜻하고 슬라이싱을 실행하면 해당 위치에서 가져온다.
print(tensor[1:, 2:])
print(tensor)
print(tensor.shape)

First row: tensor([0.4997, 0.0000, 0.1058, 0.2061])
First column: tensor([0.4997, 0.1672, 0.0813, 0.9977])
Last column: tensor([0.2061, 0.6372, 0.1055, 0.7101])
tensor([[0.3738, 0.6372],
        [0.1970, 0.1055],
        [0.4878, 0.7101]])
tensor([[0.4997, 0.0000, 0.1058, 0.2061],
        [0.1672, 0.0000, 0.3738, 0.6372],
        [0.0813, 0.0000, 0.1970, 0.1055],
        [0.9977, 0.0000, 0.4878, 0.7101]])
torch.Size([4, 4])


In [44]:
# dim을 0으로 설정하면 1차원, 1로 설정하면 2차원에 list 안의 텐서들을 연결한다.

tensor2 = torch.ones(4,4)
t1 = torch.cat([tensor2, tensor2, tensor2], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([4, 12])


In [46]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(y1)
print(y2)
print(y3)
print(z1)
print(z2)
print(z3)

tensor([[0.3034, 0.2544, 0.0832, 0.6965],
        [0.2544, 0.5737, 0.1544, 0.8016],
        [0.0832, 0.1544, 0.0565, 0.2521],
        [0.6965, 0.8016, 0.2521, 1.7375]])
tensor([[0.3034, 0.2544, 0.0832, 0.6965],
        [0.2544, 0.5737, 0.1544, 0.8016],
        [0.0832, 0.1544, 0.0565, 0.2521],
        [0.6965, 0.8016, 0.2521, 1.7375]])
tensor([[0.3034, 0.2544, 0.0832, 0.6965],
        [0.2544, 0.5737, 0.1544, 0.8016],
        [0.0832, 0.1544, 0.0565, 0.2521],
        [0.6965, 0.8016, 0.2521, 1.7375]])
tensor([[0.2497, 0.0000, 0.0112, 0.0425],
        [0.0279, 0.0000, 0.1397, 0.4060],
        [0.0066, 0.0000, 0.0388, 0.0111],
        [0.9953, 0.0000, 0.2379, 0.5043]])
tensor([[0.2497, 0.0000, 0.0112, 0.0425],
        [0.0279, 0.0000, 0.1397, 0.4060],
        [0.0066, 0.0000, 0.0388, 0.0111],
        [0.9953, 0.0000, 0.2379, 0.5043]])
tensor([[0.2497, 0.0000, 0.0112, 0.0425],
        [0.0279, 0.0000, 0.1397, 0.4060],
        [0.0066, 0.0000, 0.0388, 0.0111],
        [0.9953, 0.0000, 0.23

In [51]:
agg = tensor.mean()
agg_item = agg.item()
print(agg_item, type(agg_item))

print(agg.item())

0.28556764125823975 <class 'float'>
0.28556764125823975


In [53]:
# in-place 연산으로 접미사 '_'를 붙임

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[5.4997, 5.0000, 5.1058, 5.2061],
        [5.1672, 5.0000, 5.3738, 5.6372],
        [5.0813, 5.0000, 5.1970, 5.1055],
        [5.9977, 5.0000, 5.4878, 5.7101]]) 

tensor([[10.4997, 10.0000, 10.1058, 10.2061],
        [10.1672, 10.0000, 10.3738, 10.6372],
        [10.0813, 10.0000, 10.1970, 10.1055],
        [10.9977, 10.0000, 10.4878, 10.7101]])


### NumPy 변환

In [54]:
# cpu 상의 텐서와 numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [55]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [58]:
n = np.ones(5)
t = torch.from_numpy(n)

print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [59]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
